language: node_js
node_js:
  - "5.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp

script: gulp --production
after_script:
  - cat coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
